# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7605161e268df6e7210ee2bee389490134d4fbd79e61073d2df9a7f1b8507d44408ab2e6946ed75820ed109fd774e2b59572fd3398fd082a5e73491b114a59

test:
  secret_key_base: bde52ab60e50e5363fb7442339808f0750f163ba5c5a1f86d8a80e9b9bd5d461fa6e964e24c00391b04c31f217ed4dab1e2c6fbf2f3bd70ec2f349de92f652ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
