# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e69a36c6d0de7cb825f9b8b18bcbbadf698d8b6f8e1da27ee1022e275b83ef3ccdd7440c778bb33ede53f7dd3d8a44bdc06a66310dd8cda5312f41643997043e

test:
  secret_key_base: 7435030044dcf831df050c4e67d02f8705be6aed42799e6291cc26f832968d20a5fc6499a49b782552371d284becdd77af5b4d5f0b9e896cd5a2c03d33428338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
