# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 309416973e3687c48db9b4d97fdb1821fb07baba3350a309816da8d9ce97c9699e2fbfea17f09fc813e22302d6f7838424ce82abc6139845636f48de06802308

test:
  secret_key_base: ed0b4eaf3094e0c1ca64f496e45dcab4d133143e104291ed835a66b69402b23fc367ac62297d3800328a6dfcba414842e6e919bdf5b697ea37458769a84984f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
